FROM mcr.microsoft.com/azure-functions/dotnet:3.0-dotnet3-core-tools

RUN curl -Lo /usr/local/bin/bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64 \
    && chmod +x /usr/local/bin/bicep
